### PR TITLE
fix: graph timeframe updates after website idle

### LINKED ISSUE #155: Graph doesn't update to the appropriate timeframe once the website has been idle
### Description
Once the site has become idle and you return to the site, the graph doesn't update to the 24 hour timeframe or allow you to move the cursor to different times on the graph. The percentage change becomes 0%.

### Expected Behavior
Once you return to the web page the graph should update to the previous 24 hour period and the cursor should slide on the graph.

image

### Actual Behavior
The graph doesn't update to the previous 24 hours and the percentage change figure doesn't update.

image

### Steps to Reproduce

1. Leave the site idle. In my case overnight
2. Return to site and try to operate the graph

### Context
Provides inaccurate information

### Your Environment
Windows 10 Pro
Chrome browser

### PR DESCRIPTION
**Pull request by Matehoo**
## Description
Refetches dataset after last data point is older than 1 minute.
Added `react-page-visibility` for stopping refetching if the tab is not visible.

## Related Issue
Fixes: #155

### CODE REVIEW

File: src/pages/TradePage/TradePage.tsx [hunk 1]
```diff
@@ -205,6 +212,44 @@ export const TradeChart = ({
...
+    if (
+      !isVisible ||
+      historicalBalancesLoading ||
+      datasetRefreshing
+    )
+      return;
+
+    const refetchHistoricalBalancesData = () => {
+      if (
+        !datasetRefreshing &&
```
Comment (maht0rz) [inline src/pages/TradePage/TradePage.tsx]: this would also prevent the from/to from being updated, while the query is already in flight. I don't think this is 100% desired behavior, is it?

File: src/pages/TradePage/TradePage.tsx [hunk 2]
```diff
@@ -205,6 +212,44 @@ export const TradeChart = ({
...
+        (!dataset?.length || 
+          dataset?.[dataset?.length - 1]?.x <= new Date().getTime() - lastRecordOutdatedBy)
```
Comment (maht0rz) [inline src/pages/TradePage/TradePage.tsx]: lodash -> `last()`

File: src/pages/TradePage/TradePage.tsx (hunk 1 above)
Comment (maht0rz) [reply src/pages/TradePage/TradePage.tsx]: also please use `networkStatus` here

**Review by maht0rz — CHANGES_REQUESTED** [review]
Please address the comments before we can proceed to QA/testing.

**Comment by mckrava** [comment]
:page_with_curl: **Basilisk UI reporter** <br /> _Report has been triggered by commit [forgotten merge conflicts (ee199cbb2e03c7bb2c93ea38f6aaaed5eaae2fec)](https://github.com/galacticcouncil/Basilisk-ui/commit/ee199cbb2e03c7bb2c93ea38f6aaaed5eaae2fec)_ <hr />:small_blue_diamond: **App/Storybook build:** <br />    - Status: :white_check_mark: _Built_ <hr />:small_blue_diamond: **App/Storybook deployment:** <br />    - Status: :white_check_mark: _Deployed_     <br />    - [Application build page](https://basilisk-testnet.hydration.cloud/fix/155-graph-doesnt-update-to-the-appropriate-timeframe-once-the-website-has-been-idle/app) <br />    - [Storybook build page](https://basilisk-testnet.hydration.cloud/fix/155-graph-doesnt-update-to-the-appropriate-timeframe-once-the-website-has-been-idle/storybook)    <hr />:small_blue_diamond: **App E2E tests:** <br />    - Status: :no_entry_sign: _Failed_ <hr />:small_blue_diamond: **Available artifacts:** <br />- [app-build-files](https://github.com/galacticcouncil/Basilisk-ui/suites/6263670241/artifacts/223491718) <br />- [gh-actions-scripts](https://github.com/galacticcouncil/Basilisk-ui/suites/6263670241/artifacts/223491719) <br />- [sb-build-files](https://github.com/galacticcouncil/Basilisk-ui/suites/6263670241/artifacts/223491720) <br />- [app-build-files](https://github.com/galacticcouncil/Basilisk-ui/suites/6263670233/artifacts/223498008) <br />- [app-e2e-tests-testnet-sandbox-logs](https://github.com/galacticcouncil/Basilisk-ui/suites/6263670233/artifacts/223498009) <br />- [sb-build-files](https://github.com/galacticcouncil/Basilisk-ui/suites/6263670233/artifacts/223498010) <br />

**Review by maht0rz — APPROVED** [review]
lgtm
